openapi: 3.0.0

components:
  examples:
    entity_search:
      value:
        name: Example search
        criteria:
          input_csv_file_path: entity_names.csv
          query:
            terms:
              "1":
                scope: match_any
                operator: is
                attribute: party_fullname
                condition: OR
                proximity: "-1"
                search_terms:
                  - client_party_name
                additional_attributes:
                  - field: party_entity_type
                    value: 1
            criteria: "(1)"
          filters:
            - field: filing_date
              options:
                - field: last_n_days
                  options:
                    - "90"
            - field: created_date
              options:
                - field: last_n_days
                  options:
                    - "17"
            - field: jurisdiction
              options:
                - field: court_system
                  options:
                    - 73
            - field: case_type
              options:
                - field: group
                  options:
                    - 1
          max_result: "10000"
          sort_field: filing_date_ts
        export_options:
          file_extension: csv
          data:
            case:
              export_file: true
              file_headers:
                - matched_party_name
                - case_url
                - case_id
                - case_name
                - case_number
                - filing_date
                - case_type_caetgory
                - case_type_subcategory
                - case_type
                - case_status_category
                - case_status
                - party_type
                - party_representation_type
                - party_entity_type
              input_file_fields:
                - client_party_id
                - client_party_name
            party:
              export_file: true
              file_headers:
                - matched_party_name
                - case_id
                - party_type
                - party_representation_type
                - party_entity_type
                - party_attorney
                - party_attorney_firm
              row_per_attorney: true
              input_file_fields:
                - client_party_id
                - client_party_name
          one_time_export_criteria:
            from_filing_date: "2015-01-01"
            to_filing_date: "2020-01-15"
        is_enabled: true
        schedule:
          type: days_of_month
          args:
            - 1
            - 16
        webhook:
          - http://callback_here_on_success.com/
        run_after_create: false

    query_search:
      value:
        name: Example search
        criteria:
          search_query:
            query:
              terms:
                "1":
                  scope: match_any
                  operator: is
                  attribute: party_fullname
                  condition: OR
                  proximity: "-1"
                  search_terms:
                    - Robert D
                  additional_attributes:
                    - field: party_type
                      value: 1
              criteria: "(1)"
            filters:
              - field: filing_date
                options:
                  - field: last_n_days
                    options:
                      - "90"
              - field: created_date
                options:
                  - field: last_n_days
                    options:
                      - "16"
              - field: jurisdiction
                options:
                  - field: court_system
                    options:
                      - 73
              - field: case_type
                options:
                  - field: group
                    options:
                      - 1
            page: 1
            sort_by: desc
            max_result: "10000"
            sort_field: filing_date_ts
            items_per_page: 10
        export_options:
          file_extension: csv
          export_file_data_types:
            - case
            - party
          data:
            case:
              export_file: false
              file_headers:
                - case_url
                - case_id
                - case_name
                - case_number
                - filing_date
                - case_type_caetgory
                - case_type_subcategory
                - case_type
                - case_status_category
                - case_status
                - party_type
                - party_representation_type
                - party_entity_type
              input_file_fields: []
            party:
              export_file: true
              file_headers:
                - party_name
                - case_id
                - party_type
                - party_representation_type
                - party_entity_type
                - party_attorney
                - party_attorney_firm
              row_per_attorney: true
              input_file_fields: []
            attorney:
              export_file: false
              file_headers:
                - case_id
                - party_name
                - party_type
                - party_entity_type
                - party_reprsentation_type
                - attorney_fullname
                - attorney_bar_number
                - attorney_law_firm
                - attorney_phone_num
                - attorney_fax_num
                - attorney_street_address
                - attorney_bar_city
                - attorney_city
                - attorney_country
                - attorney_zip
                - attorney_email_ids
              row_per_party: true
              input_file_fields: []
          one_time_export_criteria:
            from_filing_date: "2015-01-01"
            to_filing_date: "2020-01-15"
        is_enabled: true
        schedule:
          type: days_of_week
          args:
            - 1
            - 2
            - 3
        webhook:
          - http://callback_here_on_success.com/
        run_after_create: false

    id_search:
      value:
        name: Example search
        criteria:
          search_id: 25
          range:
            from: 500
            to: 1000
        export_options:
          file_extension: csv
          export_file_data_types:
            - case
            - party
          data:
            case:
              export_file: true
              file_headers:
                - case_url
                - case_id
                - case_name
                - case_number
                - filing_date
                - case_type_caetgory
                - case_type_subcategory
                - case_type
                - case_status_category
                - case_status
                - party_type
                - party_representation_type
                - party_entity_type
              input_file_fields: []
            party:
              export_file: true
              file_headers:
                - party_name
                - case_id
                - party_type
                - party_representation_type
                - party_entity_type
                - party_attorney
                - party_attorney_firm
              row_per_attorney: true
              input_file_fields: []
          one_time_export_criteria: {}
        run_after_create: true
    case_id_search:
      value:
        name: Example search
        criteria:
          case_keys:
            - FJCRSHJPIAYUUFQWHRKGRBDEMBIRE0920
            - FJCRSHJPIAYUUFQWHRKGRBDEMBIRE0542
        export_options:
          file_extension: csv
          export_file_data_types:
            - case
            - party
          data:
            case:
              export_file: true
              file_headers:
                - case_url
                - case_id
                - case_name
                - case_number
                - filing_date
                - case_type_caetgory
                - case_type_subcategory
                - case_type
                - case_status_category
                - case_status
                - party_type
                - party_representation_type
                - party_entity_type
              input_file_fields: []
            party:
              export_file: true
              file_headers:
                - party_name
                - case_id
                - party_type
                - party_representation_type
                - party_entity_type
                - party_attorney
                - party_attorney_firm
              row_per_attorney: true
              input_file_fields: []
          one_time_export_criteria: {}
        webhook:
          - http://callback_here_on_success.com/
          - http://callback_here_too_on_success.com/
        run_after_create: true
